return {
    { Id = "Practice", Name = "Dedicated Student", Goal = 20, Stat = "Points", Description = "Earn 20 Karate Points." },
    { Id = "Collector", Name = "Creature Collector", Goal = 3, Stat = "Creatures", Description = "Place 3 creatures at your base." },
    { Id = "Legendary", Name = "Legendary Friend", Goal = 1, Stat = "Legendary", Description = "Place a Sun Lion at your base." },
    { Id = "BlackBelt", Name = "Black Belt", Goal = 100, Stat = "Points", Description = "Earn 100 Karate Points." },
}
